// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ46ZNBff3TaQdIRxQ4iVeUP10NQ9_5xU',
    appId: '1:687488608801:web:eb5e65bf4a683c9eddd160',
    messagingSenderId: '687488608801',
    projectId: 'hackathone-project-7e270',
    authDomain: 'hackathone-project-7e270.firebaseapp.com',
    storageBucket: 'hackathone-project-7e270.appspot.com',
    measurementId: 'G-LRXK69H2LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq7jyWay5RK-Q8Ev3M95wnGzmgRLdxb0o',
    appId: '1:687488608801:android:5113b76c38298b9dddd160',
    messagingSenderId: '687488608801',
    projectId: 'hackathone-project-7e270',
    storageBucket: 'hackathone-project-7e270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4iwOMiKkJjtDD5aLOB803_-Q1krOXaBQ',
    appId: '1:687488608801:ios:cd5104cc280c9a41ddd160',
    messagingSenderId: '687488608801',
    projectId: 'hackathone-project-7e270',
    storageBucket: 'hackathone-project-7e270.appspot.com',
    iosBundleId: 'com.example.projects',
  );
}
